spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/reddit_clone
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
    show-sql: true
